# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImperialShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('tie', models.BooleanField(default=False, verbose_name='TIE')),
                ('large', models.BooleanField(default=False)),
            ],
        ),
    ]
