# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotac', '0004_auto_20160725_2101'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotac.Mission')),
            ],
        ),
    ]
