# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0002_campaignmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMissionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignMission')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_skill', models.IntegerField(default=2)),
                ('callsign', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PilotOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.PilotOwner'),
        ),
        migrations.AddField(
            model_name='campaignmissionparticipant',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Pilot'),
        ),
        migrations.AlterUniqueTogether(
            name='pilot',
            unique_together=set([('callsign',)]),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmissionparticipant',
            unique_together=set([('pilot', 'mission')]),
        ),
    ]
