# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20160725_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('xp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.Xp')),
            ],
            bases=('campaign.xp',),
        ),
        migrations.CreateModel(
            name='GuardianAssist',
            fields=[
                ('xp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.Xp')),
            ],
            bases=('campaign.xp',),
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('xp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.Xp')),
                ('elite', models.BooleanField(default=False)),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.ImperialShip')),
            ],
            bases=('campaign.xp',),
        ),
        migrations.CreateModel(
            name='KillAssist',
            fields=[
                ('xp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.Xp')),
            ],
            bases=('campaign.xp',),
        ),
        migrations.CreateModel(
            name='MissieonBonus',
            fields=[
                ('xp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.Xp')),
                ('description', models.CharField(max_length=20)),
            ],
            bases=('campaign.xp',),
        ),
        migrations.AddField(
            model_name='xp',
            name='pilotmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignMissionParticipant'),
        ),
    ]
