# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20160725_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='imperialship',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
