# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaignmission_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Squadron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SquadronMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('pilot_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.PilotOwner')),
                ('squadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Squadron')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='squadronmember',
            unique_together=set([('squadron', 'pilot_owner')]),
        ),
    ]
