# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20160810_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='invite_only',
            field=models.BooleanField(default=True),
        ),
    ]
