# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_squadron_invite_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadron',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
