# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
