# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotac', '0002_mission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemysquadron',
            name='ai',
            field=models.CharField(choices=[('S', 'Strike'), ('A', 'Attack'), ('X', 'Special'), ('F', 'Flee')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
