# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotac', '0003_enemysquadron_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemysquadron',
            name='ai',
            field=models.CharField(choices=[('S', 'Strike'), ('A', 'Attack'), ('X', 'Special'), ('F', 'Flee')], max_length=1, verbose_name='AI'),
        ),
    ]
